### PR TITLE
Package re-org to pass travis testing

### PR DESCRIPTION
**Pull request by danielturek**
Carl, let me say upfront that I'm not necessarily requesting that we merge this PR.  I'm putting the option out there for discussion.  I won't be offended if we decide not to.  I, myself, am not 100% happy with the path I went down and the ensuing reorganization.

This all stemmed from the fact that NIMBLE's dynamically generated R reference class definitions, which are created when nimbleFunctions are defined as internal package functions, are not properly located when the package is loaded.  This is a problem I'm actively looking into otherwise, since we (the NIMBLE team, that is) have a vested interest in fixing.  What I'm proposing here is only a workaround, to get travis to successfully run (and pass) our tests.

This PR introduces changes in the package organization: any nimbleFunctions defined as package functions would have to be defined instead in `inst/include/nfs.R`.  This file is then included with the installed package, and this script is run at package load time (which defines the nimbleFunctions locally; per the instruction of `R/zzz.R` which contains a call to `.onAttach()`).  Any nimbleFunctions defined in this manner may then be used internally in package functions.

Following from this change, for reasons unknown to me, I then had to change the `.travis.yml` installation instructions to do manual installs of all necessary packages.  In addition, I had to explicitly include the `script: Rscript tests/testthat.R` instruction.  I'm not sure why.  Perhaps your greater experience with travis will provide some insight?

Another point I should mention, is it seems we won't be passing `check()` anytime soon.  It's not happy with a number of the things going on with the use of NIMBLE.  The repercussion here is that we couldn't go onto CRAN, which is more a problem for NIMBLE than for gpmanagement.  I just thought I should mention this.

I welcome your thoughts on all of the above.

### CODE REVIEW

**Comment by cboettig** [comment]
Wow, interesting.  Yeah, not sure what is up with Travis, I'll take a look.  

Is it obvious to you why R fails when the `gpPred` function is in `R` but not when it's just sourced in?

p.s. aren't you on holiday? ;-)

**Comment by cboettig** [comment]
Looks like your travis weirdness may have arisen because you made use of `before_install:`, which for some strange reason runs before `r-travis` has had a chance to install `devtools` (or perhaps is overriding that step in `r-travis`; anyway, doesn't seem like the ideal behavior for `r-travis` so I opened an issue: https://github.com/craigcitro/r-travis/issues/158) .  

Simply installing `devtools` as the first `before_install` command should fix this; meaning that one can use the `r_github_packages:` directive, and can rely on `r-travis` to successfully install all dependencies/suggests etc listed in the DESCRIPTION without having to list them in travis.  (though travis builds a bit faster if we keep the `r_packages`; it's so slow already that we may as well drop those lines and have a more consise travis file which will install the dependencies from source).

Unfortunately, the igraph issue makes a mess of things now, because `install_github()` erroneously upgrades me to the latest igraph even after I've gone through the trouble of manually installing an older one:  https://github.com/hadley/devtools/issues/863.  Of course we can work around this, but it's a bit more ugly than it should be: https://github.com/cboettig/gpmanagement/blob/bd1f9004ae97a94764aa0b752aca3c7c9ba695fc/.travis.yml

**Comment by danielturek** [comment]
Ok, this is interesting fallout from the (seemingly simple) travis issue.  Thanks for looking into the travis package installation issues in such detail, and filing the appropriate issues with r-travis, etc.

I'm hopeful that:
(1) We (NIMBLE) will get the new igraph sorted out ASAP, which will simplify things somewhat, and
(2) We (NIMBLE) will sort out NFs needing to be sourced directly into the R session.

Yes, unfortunately, it's reasonably clear to me why (2) is the case -- R Reference Class class definitions are *always* assigned into the global environment, which usually works fine for purposes of scoping.  However, creating such definitions (as occurs when a NF is defined) at package build time results in the definitions *not* being part of the package namespace, and hence they are not available in subsequent R sessions which load said package.

We'll fix this problem if we can, but for the meantime, I suggest we proceed using the new `gpmanagement` package organization.  Sorry to disrupt your typical workflows.  And thanks again for the extra time you put in figuring out what's going on in travis, not to mention sorting out the [new] igraph issue.

**Comment by cboettig** [comment]
Sounds good.  Yeah, the new organization isn't a problem, just curious about what was going on -- haven't used ReferenceClasses much.  Seems strange that they would always be defined to the global environment; how do people write packages with those things?  Anyway, not something we need to solve to go forward. 

Yup, fixing the igraph thing should streamline install & testing, and obviously is a more immediate issue for NIMBLE.  I think @gaborcsardi has mentioned breaking up igraph package in the future since it's gotten so large now, so it might be a moving target for a bit longer; we might check in with him directly (If you haven't met Gabor, he's super nice and responsive so I'd encourage you to reach out to him if the igraph updating is causing issues).  

Anyway, gonna forge ahead with some runs on simulated data to make sure I have a handle on what's going on, and will ping you.  I still have some work to do in getting the second key algorithm up to speed as well; the part which does the optimal control.  Once that machinery is in place we should be able to roll.

**Comment by danielturek** [comment]
Sounds good.  Keep in touch.

**Comment by gaborcsardi** [comment]
So what is the igraph issue, guys?

Btw. I'll break up igraph, but in a backward compatible way. So no worries. Enough API breakage for this year.

**Comment by danielturek** [comment]
I tracked down the change in `igraph` version 1.0.x.  The `topo_sort()` function no longer returns a numeric vector, as it used to (version 0.7.1), and as the documentation states:

Value: A numeric vector containing vertex ids in topologically sorted order.

I found that re-casting the return value of `topo_sort()` using `as.numeric()` produces a numeric vector identical to previous.  So I've updated the `nimble` package accordingly.  But you might consider fixing this (or changing the documentation) in `igraph`.

Carl -- `nimble@stable` should now work with the new 1.0.x versions of `igraph`

Gábor -- not that you need one, but here's a simple reproducible example:

library(igraph)
graph <- graph.empty()
graph <- add.vertices(graph, 2, name = c('a', 'b'))
graph <- add.edges(graph, c(1, 2))
toposortReturn <- topological.sort(graph, mode = 'out')
print(toposortReturn)
'## + 2/2 vertices, named:
'## [1] a b
class(toposortReturn)
'## [1] "igraph.vs"

**Comment by cboettig** [comment]
Nice work! You might want to file an issue or PR in https://github.com/igraph/rigraph/issues just to make sure Gábor sees it.

**Comment by danielturek** [comment]
Good idea.  Done.

**Comment by cboettig** [comment]
@danielturek Shouldn't we be able to build nimble from the stable branch using the latest `igraph` now? Looks like my travis install is still failing when using the current `igraph` version: https://travis-ci.org/cboettig/gpmanagement/builds/71136833#L3216

**Comment by gaborcsardi** [comment]
This does not seem to be an igraph issue to me.

**Comment by cboettig** [comment]
Right, looks like a `nimble` issue, but I thought https://github.com/nimble-dev/nimble/commit/48b2e5267bc68ed6c371db484fc989e0c28d19af would have fixed it.  @danielturek probably knows what's going on but it's over my head.

**Comment by danielturek** [comment]
This is a tough one.  The previous fix I made *did* solve the first problem introduced in `igraph` 1.x.x.  This is another such problem.

I narrowed it down to the fact that the new `igraph` links to compiled methods (which it didn't previously) which somehow mask NIMBLE's ability to locate `dpotrf` in the system LAPACK.  For example, those in:
`igraph / src / CHOLMOD / Supernodal / t_cholmod_super_numeric.c`
I'm not sure how this is the case.

I've raised this with the NIMBLE team here at Berkeley, since it's a problem that the NIMBLE package cannot be loaded with `igraph` 1.x.x is installed.  So it's in our court, and we're working on it.

Carl, this is obviously a high priority for us here, so we'll take care of it ASAP, which will then solve our problem for `gpmanagement`.

**Comment by danielturek** [comment]
I think we're all sorted.  Fixed on NIMBLE.  `master` branch of `gpmanagement` is now passing travis testing, using the new `igraph`.  You may well be able to tidy up the `.travis.yml` file even further.  If so, please do so.

Let me know if this continues to be an issue.

**Comment by hadley** [comment]
@danielturek WRT the ref classes issue, I think you have two options:

1. Use R6 - Winston carefully thought this through to avoid the cross-package inheritance problem shown by RC. Switching from RC to R6 is moderately painful - it's a fairly mechanical transformation and we've done it for a few package. It's probably a couple of hours.

1. Wait for the next version of R. John Chambers has introduced some fixes for the underlying problem to ref classes. I haven't looked closely at what he's done, or tested it, but it might be worth looking to see if R-devel solves your problem.

**Pull request merged**
